name: flutt_appicon
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  ios: false
  android: true
  #image_path_ios: "lib/assets/images/edea_icon_two.png"
  image_path_android: "assets/icons/icon1.png"
  #adaptive_icon_background: "lib/assets/images/edea_launcher_background2.png"
  #adaptive_icon_foreground: "lib/assets/images/edea_launcher_foreground.png"
  web:
    generate: false   
  windows:
    generate: false    
  macos:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/icons/